### ISSUE TITLE
Colors not readable on dark KDE theme

### ISSUE THREAD

**Issue by saleyn** [artplant/vprof#1]
The grid's alternative row color is not readable:

![image](https://cloud.githubusercontent.com/assets/272543/13797535/ab2b66e8-eae4-11e5-8565-ec01142d6491.png)

**Comment by thehangedman** [comment]
I changed grid to use system colours instead of hardcoded:
8bc95577a9e4b6de2a7ce2157f2f004dd0fb6c8e
I can't test on KDE but it should fix the issue.

**Comment by saleyn** [comment]
That did it. Thanks.
